"""initial

Revision ID: 0bb37c3dbf1d
Revises: 
Create Date: 2026-05-06 20:28:27.220305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bb37c3dbf1d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campos_recomendacion', sa.Column('opciones_padre', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'campos_recomendacion', 'campos_recomendacion', ['campo_padre_id'], ['id'], ondelete='SET NULL')
    op.add_column('diagnostico_campos', sa.Column('opciones_padre', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'diagnostico_campos', 'diagnostico_campos', ['campo_padre_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'diagnostico_planta', 'plantas', ['planta_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'diagnostico_planta', 'diagnosticos', ['diagnostico_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'diagnostico_tipos', 'monitoreos', ['monitoreo_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'evidencias', 'diagnosticos', ['diagnostico_id'], ['id'])
    op.create_foreign_key(None, 'evidencias', 'recomendaciones', ['recomendacion_id'], ['id'])
    op.create_foreign_key(None, 'labores', 'recomendaciones', ['recomendacion_id'], ['id'])
    op.create_foreign_key(None, 'recomendacion_items', 'recomendaciones', ['recomendacion_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'recomendaciones', 'diagnosticos', ['diagnostico_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recomendaciones', type_='foreignkey')
    op.drop_constraint(None, 'recomendacion_items', type_='foreignkey')
    op.drop_constraint(None, 'labores', type_='foreignkey')
    op.drop_constraint(None, 'evidencias', type_='foreignkey')
    op.drop_constraint(None, 'evidencias', type_='foreignkey')
    op.drop_constraint(None, 'diagnostico_tipos', type_='foreignkey')
    op.drop_constraint(None, 'diagnostico_planta', type_='foreignkey')
    op.drop_constraint(None, 'diagnostico_planta', type_='foreignkey')
    op.drop_constraint(None, 'diagnostico_campos', type_='foreignkey')
    op.drop_column('diagnostico_campos', 'opciones_padre')
    op.drop_constraint(None, 'campos_recomendacion', type_='foreignkey')
    op.drop_column('campos_recomendacion', 'opciones_padre')
    # ### end Alembic commands ###
