"""sync recomendaciones

Revision ID: 200b2c03427a
Revises: 89cde01cd0a5
Create Date: 2026-05-06 18:55:49.075981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '200b2c03427a'
down_revision: Union[str, None] = '89cde01cd0a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # ─── CREACIÓN DE TABLAS NUEVAS ───────────────────────────────────────
    op.create_table('monitoreos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('programa_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['programa_id'], ['programas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoreos_id'), 'monitoreos', ['id'], unique=False)
    
    op.create_table('programas_inventario_tipos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('programa_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['programa_id'], ['programas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programas_inventario_tipos_id'), 'programas_inventario_tipos', ['id'], unique=False)
    
    op.create_table('diagnostico_tipos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('programa_id', sa.Integer(), nullable=False),
    sa.Column('monitoreo_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['monitoreo_id'], ['monitoreos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['programa_id'], ['programas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnostico_tipos_id'), 'diagnostico_tipos', ['id'], unique=False)
    
    op.create_table('inventario_campos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_id', sa.Integer(), nullable=False),
    sa.Column('nombre_campo', sa.String(length=100), nullable=False),
    sa.Column('tipo_dato', sa.String(length=20), nullable=False),
    sa.Column('requerido', sa.Boolean(), nullable=True),
    sa.Column('opciones', sa.JSON(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('ancho', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tipo_id'], ['programas_inventario_tipos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventario_campos_id'), 'inventario_campos', ['id'], unique=False)
    
    op.create_table('items_inventario_programa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inventario', sa.Date(), nullable=True),
    sa.Column('cantidad_disponible', sa.Float(), nullable=True),
    sa.Column('unidad_medida', sa.String(length=50), nullable=True),
    sa.Column('valores', sa.JSON(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tipo_id'], ['programas_inventario_tipos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_inventario_programa_id'), 'items_inventario_programa', ['id'], unique=False)
    
    op.create_table('lote_cultivo',
    sa.Column('lote_id', sa.Integer(), nullable=False),
    sa.Column('cultivo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cultivo_id'], ['cultivos_especies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lote_id', 'cultivo_id')
    )
    
    op.create_table('plantas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=False),
    sa.Column('surco', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plantas_codigo'), 'plantas', ['codigo'], unique=True)
    op.create_index(op.f('ix_plantas_id'), 'plantas', ['id'], unique=False)
    
    op.create_table('campos_recomendacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subtipo_id', sa.Integer(), nullable=False),
    sa.Column('nombre_campo', sa.String(length=100), nullable=False),
    sa.Column('etiqueta', sa.String(length=150), nullable=False),
    sa.Column('tipo_dato', sa.String(length=20), nullable=False),
    sa.Column('requerido', sa.Boolean(), nullable=True),
    sa.Column('opciones', sa.JSON(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('campo_padre_id', sa.Integer(), nullable=True),
    sa.Column('opciones_padre', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campo_padre_id'], ['campos_recomendacion.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subtipo_id'], ['diagnostico_tipos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campos_recomendacion_id'), 'campos_recomendacion', ['id'], unique=False)
    
    op.create_table('diagnostico_campos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_id', sa.Integer(), nullable=False),
    sa.Column('nombre_campo', sa.String(length=100), nullable=False),
    sa.Column('etiqueta', sa.String(length=150), nullable=False),
    sa.Column('tipo_dato', sa.String(length=20), nullable=False),
    sa.Column('requerido', sa.Boolean(), nullable=True),
    sa.Column('opciones', sa.JSON(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('campo_padre_id', sa.Integer(), nullable=True),
    sa.Column('opciones_padre', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campo_padre_id'], ['diagnostico_campos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tipo_id'], ['diagnostico_tipos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnostico_campos_id'), 'diagnostico_campos', ['id'], unique=False)
    
    op.create_table('diagnostico_planta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diagnostico_id', sa.Integer(), nullable=True),
    sa.Column('planta_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['diagnostico_id'], ['diagnosticos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['planta_id'], ['plantas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnostico_planta_id'), 'diagnostico_planta', ['id'], unique=False)
    
    op.create_table('recomendacion_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recomendacion_id', sa.Integer(), nullable=False),
    sa.Column('inventario_item_id', sa.Integer(), nullable=True),
    sa.Column('cantidad_sugerida', sa.Float(), nullable=True),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inventario_item_id'], ['items_inventario_programa.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recomendacion_id'], ['recomendaciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recomendacion_items_id'), 'recomendacion_items', ['id'], unique=False)

    # ─── ELIMINACIONES COMENTADAS (TABLAS VIEJAS QUE AÚN EXISTEN) ─────
    # op.drop_index('ix_categorias_inventario_id', table_name='categorias_inventario')
    # op.drop_table('categorias_inventario')
    # op.drop_index('ix_movimientos_herramientas_id', table_name='movimientos_herramientas')
    # op.drop_table('movimientos_herramientas')
    # op.drop_index('ix_movimientos_insumos_id', table_name='movimientos_insumos')
    # op.drop_table('movimientos_insumos')
    # op.drop_index('ix_herramientas_id', table_name='herramientas')
    # op.drop_table('herramientas')
    # op.drop_index('ix_asignaciones_herramientas_id', table_name='asignaciones_herramientas')
    # op.drop_table('asignaciones_herramientas')
    # op.drop_index('ix_insumos_id', table_name='insumos')
    # op.drop_table('insumos')
    # op.drop_column('cultivos_especies', 'fecha_inicio')
    # op.drop_column('cultivos_especies', 'duracion_dias')
    
    # ─── MODIFICACIONES EXISTENTES QUE SÍ QUEREMOS APLICAR ──────────────
    op.add_column('diagnosticos', sa.Column('programa_id', sa.Integer(), nullable=False))
    op.add_column('diagnosticos', sa.Column('tipo_monitoreo_id', sa.Integer(), nullable=True))
    op.add_column('diagnosticos', sa.Column('usuario_id', sa.Integer(), nullable=False))
    op.add_column('diagnosticos', sa.Column('diagnostico_tipo_id', sa.Integer(), nullable=True))
    op.add_column('diagnosticos', sa.Column('tipo_diagnostico', sa.String(length=100), nullable=False))
    op.add_column('diagnosticos', sa.Column('condiciones_dia', sa.String(length=50), nullable=False))
    op.add_column('diagnosticos', sa.Column('formulario', sa.JSON(), nullable=True))
    op.add_column('diagnosticos', sa.Column('estado_revision', sa.String(length=30), nullable=False))
    op.alter_column('diagnosticos', 'lote_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('diagnosticos_estudiante_id_fkey', 'diagnosticos', type_='foreignkey')
    op.drop_constraint('diagnosticos_docente_id_fkey', 'diagnosticos', type_='foreignkey')
    op.create_foreign_key(None, 'diagnosticos', 'monitoreos', ['tipo_monitoreo_id'], ['id'])
    op.create_foreign_key(None, 'diagnosticos', 'programas', ['programa_id'], ['id'])
    op.create_foreign_key(None, 'diagnosticos', 'usuarios', ['usuario_id'], ['id'])
    op.create_foreign_key(None, 'diagnosticos', 'diagnostico_tipos', ['diagnostico_tipo_id'], ['id'])
    op.drop_column('diagnosticos', 'estudiante_id')
    op.drop_column('diagnosticos', 'observaciones')
    op.drop_column('diagnosticos', 'descripcion')
    op.drop_column('diagnosticos', 'docente_id')
    op.drop_column('diagnosticos', 'tipo')
    op.drop_column('diagnosticos', 'estado')
    op.drop_column('diagnosticos', 'fecha_revision')
    
    op.add_column('labores', sa.Column('inventario_item_id', sa.Integer(), nullable=True))
    op.add_column('labores', sa.Column('cantidad_usada', sa.Float(), nullable=True))
    op.add_column('labores', sa.Column('dosis_aplicada', sa.Float(), nullable=True))
    op.add_column('labores', sa.Column('unidad_dosis', sa.String(length=50), nullable=True))
    op.alter_column('labores', 'trabajador_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'labores', 'items_inventario_programa', ['inventario_item_id'], ['id'])
    
    op.add_column('lotes', sa.Column('surcos', sa.Integer(), nullable=False))
    op.add_column('lotes', sa.Column('plantas_por_surco', sa.Integer(), nullable=False))
    op.drop_constraint('lotes_cultivo_id_fkey', 'lotes', type_='foreignkey')
    op.drop_column('lotes', 'cultivo_id')
    op.drop_column('lotes', 'nombre_cultivo')
    
    op.add_column('recomendaciones', sa.Column('subtipo_id', sa.Integer(), nullable=True))
    op.add_column('recomendaciones', sa.Column('formulario_recomendacion', sa.JSON(), nullable=True))
    op.add_column('recomendaciones', sa.Column('inventario_item_id', sa.Integer(), nullable=True))
    op.add_column('recomendaciones', sa.Column('cantidad_sugerida', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'recomendaciones', 'items_inventario_programa', ['inventario_item_id'], ['id'])
    op.create_foreign_key(None, 'recomendaciones', 'diagnostico_tipos', ['subtipo_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recomendaciones', type_='foreignkey')
    op.drop_constraint(None, 'recomendaciones', type_='foreignkey')
    op.drop_column('recomendaciones', 'cantidad_sugerida')
    op.drop_column('recomendaciones', 'inventario_item_id')
    op.drop_column('recomendaciones', 'formulario_recomendacion')
    op.drop_column('recomendaciones', 'subtipo_id')
    
    op.add_column('lotes', sa.Column('nombre_cultivo', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('lotes', sa.Column('cultivo_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('lotes_cultivo_id_fkey', 'lotes', 'cultivos_especies', ['cultivo_id'], ['id'])
    op.drop_column('lotes', 'plantas_por_surco')
    op.drop_column('lotes', 'surcos')
    
    op.drop_constraint(None, 'labores', type_='foreignkey')
    op.alter_column('labores', 'trabajador_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('labores', 'unidad_dosis')
    op.drop_column('labores', 'dosis_aplicada')
    op.drop_column('labores', 'cantidad_usada')
    op.drop_column('labores', 'inventario_item_id')
    
    op.add_column('diagnosticos', sa.Column('fecha_revision', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('diagnosticos', sa.Column('estado', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('diagnosticos', sa.Column('tipo', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('diagnosticos', sa.Column('docente_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('diagnosticos', sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('diagnosticos', sa.Column('observaciones', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('diagnosticos', sa.Column('estudiante_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'diagnosticos', type_='foreignkey')
    op.drop_constraint(None, 'diagnosticos', type_='foreignkey')
    op.drop_constraint(None, 'diagnosticos', type_='foreignkey')
    op.drop_constraint(None, 'diagnosticos', type_='foreignkey')
    op.create_foreign_key('diagnosticos_docente_id_fkey', 'diagnosticos', 'usuarios', ['docente_id'], ['id'])
    op.create_foreign_key('diagnosticos_estudiante_id_fkey', 'diagnosticos', 'usuarios', ['estudiante_id'], ['id'])
    op.alter_column('diagnosticos', 'lote_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('diagnosticos', 'estado_revision')
    op.drop_column('diagnosticos', 'formulario')
    op.drop_column('diagnosticos', 'condiciones_dia')
    op.drop_column('diagnosticos', 'tipo_diagnostico')
    op.drop_column('diagnosticos', 'diagnostico_tipo_id')
    op.drop_column('diagnosticos', 'usuario_id')
    op.drop_column('diagnosticos', 'tipo_monitoreo_id')
    op.drop_column('diagnosticos', 'programa_id')
    
    # op.add_column('cultivos_especies', sa.Column('duracion_dias', sa.INTEGER(), autoincrement=False, nullable=True))
    # op.add_column('cultivos_especies', sa.Column('fecha_inicio', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    
    # ─── RECREACIÓN DE TABLAS VIEJAS COMENTADA ─────────────────────────
    # op.create_table('insumos', ...)
    # op.create_index('ix_insumos_id', 'insumos', ['id'], unique=False)
    # ...
    
    op.drop_index(op.f('ix_recomendacion_items_id'), table_name='recomendacion_items')
    op.drop_table('recomendacion_items')
    op.drop_index(op.f('ix_diagnostico_planta_id'), table_name='diagnostico_planta')
    op.drop_table('diagnostico_planta')
    op.drop_index(op.f('ix_diagnostico_campos_id'), table_name='diagnostico_campos')
    op.drop_table('diagnostico_campos')
    op.drop_index(op.f('ix_campos_recomendacion_id'), table_name='campos_recomendacion')
    op.drop_table('campos_recomendacion')
    op.drop_index(op.f('ix_plantas_id'), table_name='plantas')
    op.drop_index(op.f('ix_plantas_codigo'), table_name='plantas')
    op.drop_table('plantas')
    op.drop_table('lote_cultivo')
    op.drop_index(op.f('ix_items_inventario_programa_id'), table_name='items_inventario_programa')
    op.drop_table('items_inventario_programa')
    op.drop_index(op.f('ix_inventario_campos_id'), table_name='inventario_campos')
    op.drop_table('inventario_campos')
    op.drop_index(op.f('ix_diagnostico_tipos_id'), table_name='diagnostico_tipos')
    op.drop_table('diagnostico_tipos')
    op.drop_index(op.f('ix_programas_inventario_tipos_id'), table_name='programas_inventario_tipos')
    op.drop_table('programas_inventario_tipos')
    op.drop_index(op.f('ix_monitoreos_id'), table_name='monitoreos')
    op.drop_table('monitoreos')
    # ### end Alembic commands ###