"""initial_fixed

Revision ID: 3649dd852836
Revises: 
Create Date: 2026-05-15 17:55:39.379528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3649dd852836'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('diagnostico_tipos', 'patron_arvenses',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_foreign_key(None, 'evidencias', 'recomendaciones', ['recomendacion_id'], ['id'])
    op.create_foreign_key(None, 'labores', 'recomendaciones', ['recomendacion_id'], ['id'])
    op.create_foreign_key(None, 'productos_recomendaciones', 'recomendaciones', ['recomendacion_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'recomendacion_items', 'recomendaciones', ['recomendacion_id'], ['id'], ondelete='CASCADE')
    op.add_column('recomendaciones', sa.Column('titulo', sa.String(length=200), nullable=False))
    op.add_column('recomendaciones', sa.Column('descripcion', sa.Text(), nullable=True))
    op.add_column('recomendaciones', sa.Column('tipo', sa.String(length=100), nullable=True))
    op.add_column('recomendaciones', sa.Column('estado', sa.String(length=50), nullable=True))
    op.add_column('recomendaciones', sa.Column('docente_id', sa.Integer(), nullable=False))
    op.add_column('recomendaciones', sa.Column('lote_id', sa.Integer(), nullable=False))
    op.add_column('recomendaciones', sa.Column('diagnostico_id', sa.Integer(), nullable=True))
    op.add_column('recomendaciones', sa.Column('subtipo_id', sa.Integer(), nullable=True))
    op.add_column('recomendaciones', sa.Column('formulario_recomendacion', sa.JSON(), nullable=True))
    op.add_column('recomendaciones', sa.Column('inventario_item_id', sa.Integer(), nullable=True))
    op.add_column('recomendaciones', sa.Column('cantidad_sugerida', sa.Float(), nullable=True))
    op.add_column('recomendaciones', sa.Column('fecha_creacion', sa.DateTime(), nullable=True))
    op.add_column('recomendaciones', sa.Column('fecha_aprobacion', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_recomendaciones_id'), 'recomendaciones', ['id'], unique=False)
    op.create_foreign_key(None, 'recomendaciones', 'lotes', ['lote_id'], ['id'])
    op.create_foreign_key(None, 'recomendaciones', 'items_inventario_programa', ['inventario_item_id'], ['id'])
    op.create_foreign_key(None, 'recomendaciones', 'diagnosticos', ['diagnostico_id'], ['id'])
    op.create_foreign_key(None, 'recomendaciones', 'usuarios', ['docente_id'], ['id'])
    op.create_foreign_key(None, 'recomendaciones', 'diagnostico_tipos', ['subtipo_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recomendaciones', type_='foreignkey')
    op.drop_constraint(None, 'recomendaciones', type_='foreignkey')
    op.drop_constraint(None, 'recomendaciones', type_='foreignkey')
    op.drop_constraint(None, 'recomendaciones', type_='foreignkey')
    op.drop_constraint(None, 'recomendaciones', type_='foreignkey')
    op.drop_index(op.f('ix_recomendaciones_id'), table_name='recomendaciones')
    op.drop_column('recomendaciones', 'fecha_aprobacion')
    op.drop_column('recomendaciones', 'fecha_creacion')
    op.drop_column('recomendaciones', 'cantidad_sugerida')
    op.drop_column('recomendaciones', 'inventario_item_id')
    op.drop_column('recomendaciones', 'formulario_recomendacion')
    op.drop_column('recomendaciones', 'subtipo_id')
    op.drop_column('recomendaciones', 'diagnostico_id')
    op.drop_column('recomendaciones', 'lote_id')
    op.drop_column('recomendaciones', 'docente_id')
    op.drop_column('recomendaciones', 'estado')
    op.drop_column('recomendaciones', 'tipo')
    op.drop_column('recomendaciones', 'descripcion')
    op.drop_column('recomendaciones', 'titulo')
    op.drop_constraint(None, 'recomendacion_items', type_='foreignkey')
    op.drop_constraint(None, 'productos_recomendaciones', type_='foreignkey')
    op.drop_constraint(None, 'labores', type_='foreignkey')
    op.drop_constraint(None, 'evidencias', type_='foreignkey')
    op.alter_column('diagnostico_tipos', 'patron_arvenses',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
