"""Añadir/Eliminar tablas de inicialización de datos y ajustes en modelos

Revision ID: 3a6b7c408f8d
Revises: 4b2681de4270
Create Date: 2025-10-26 16:33:52.211164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3a6b7c408f8d'
down_revision: Union[str, None] = '4b2681de4270'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias_inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorias_inventario_id'), 'categorias_inventario', ['id'], unique=False)
    op.create_table('tipos_labor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipos_labor_id'), 'tipos_labor', ['id'], unique=False)
    op.create_table('tipos_lote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipos_lote_id'), 'tipos_lote', ['id'], unique=False)
    op.create_table('granja_programa',
    sa.Column('granja_id', sa.Integer(), nullable=True),
    sa.Column('programa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['granja_id'], ['granjas.id'], ),
    sa.ForeignKeyConstraint(['programa_id'], ['programas.id'], )
    )
    op.create_table('herramientas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('cantidad_total', sa.Integer(), nullable=True),
    sa.Column('cantidad_disponible', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias_inventario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_herramientas_id'), 'herramientas', ['id'], unique=False)
    op.create_table('insumos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('programa_id', sa.Integer(), nullable=True),
    sa.Column('cantidad_total', sa.Float(), nullable=True),
    sa.Column('cantidad_disponible', sa.Float(), nullable=True),
    sa.Column('unidad_medida', sa.String(length=50), nullable=True),
    sa.Column('nivel_alerta', sa.Float(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['programa_id'], ['programas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insumos_id'), 'insumos', ['id'], unique=False)
    op.create_table('recomendaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('docente_id', sa.Integer(), nullable=True),
    sa.Column('lote_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_aprobacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['docente_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recomendaciones_id'), 'recomendaciones', ['id'], unique=False)
    op.create_table('usuario_granja',
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('granja_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['granja_id'], ['granjas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], )
    )
    op.create_table('usuario_programa',
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('programa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['programa_id'], ['programas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], )
    )
    op.create_table('movimientos_herramientas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('herramienta_id', sa.Integer(), nullable=True),
    sa.Column('labor_id', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('tipo_movimiento', sa.String(length=50), nullable=False),
    sa.Column('fecha_movimiento', sa.DateTime(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['herramienta_id'], ['herramientas.id'], ),
    sa.ForeignKeyConstraint(['labor_id'], ['labores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimientos_herramientas_id'), 'movimientos_herramientas', ['id'], unique=False)
    op.create_table('movimientos_insumos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('insumo_id', sa.Integer(), nullable=True),
    sa.Column('labor_id', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('tipo_movimiento', sa.String(length=50), nullable=False),
    sa.Column('fecha_movimiento', sa.DateTime(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['insumo_id'], ['insumos.id'], ),
    sa.ForeignKeyConstraint(['labor_id'], ['labores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimientos_insumos_id'), 'movimientos_insumos', ['id'], unique=False)
    op.drop_constraint('granjas_asesor_id_fkey', 'granjas', type_='foreignkey')
    op.drop_constraint('granjas_programa_id_fkey', 'granjas', type_='foreignkey')
    op.drop_column('granjas', 'asesor_id')
    op.drop_column('granjas', 'programa_id')
    op.add_column('labores', sa.Column('tipo_labor_id', sa.Integer(), nullable=True))
    op.add_column('labores', sa.Column('trabajador_id', sa.Integer(), nullable=True))
    op.add_column('labores', sa.Column('recomendacion_id', sa.Integer(), nullable=True))
    op.add_column('labores', sa.Column('fecha_creacion', sa.DateTime(), nullable=True))
    op.add_column('labores', sa.Column('fecha_asignacion', sa.DateTime(), nullable=True))
    op.add_column('labores', sa.Column('prioridad', sa.String(length=20), nullable=True))
    op.drop_constraint('labores_usuario_id_fkey', 'labores', type_='foreignkey')
    op.create_foreign_key(None, 'labores', 'usuarios', ['trabajador_id'], ['id'])
    op.create_foreign_key(None, 'labores', 'tipos_labor', ['tipo_labor_id'], ['id'])
    op.create_foreign_key(None, 'labores', 'recomendaciones', ['recomendacion_id'], ['id'])
    op.drop_column('labores', 'usuario_id')
    op.add_column('lotes', sa.Column('tipo_lote_id', sa.Integer(), nullable=True))
    op.add_column('lotes', sa.Column('programa_id', sa.Integer(), nullable=True))
    op.add_column('lotes', sa.Column('nombre_cultivo', sa.String(length=100), nullable=True))
    op.add_column('lotes', sa.Column('tipo_gestion', sa.String(length=100), nullable=True))
    op.add_column('lotes', sa.Column('fecha_inicio', sa.DateTime(), nullable=True))
    op.add_column('lotes', sa.Column('duracion_dias', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'lotes', 'programas', ['programa_id'], ['id'])
    op.create_foreign_key(None, 'lotes', 'tipos_lote', ['tipo_lote_id'], ['id'])
    op.drop_column('lotes', 'cultivo')
    op.drop_column('lotes', 'area')
    op.drop_column('lotes', 'fecha_creacion')
    op.add_column('programas', sa.Column('tipo', sa.String(length=50), nullable=False))
    op.add_column('programas', sa.Column('fecha_creacion', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('programas', 'fecha_creacion')
    op.drop_column('programas', 'tipo')
    op.add_column('lotes', sa.Column('fecha_creacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('lotes', sa.Column('area', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('lotes', sa.Column('cultivo', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'lotes', type_='foreignkey')
    op.drop_constraint(None, 'lotes', type_='foreignkey')
    op.drop_column('lotes', 'duracion_dias')
    op.drop_column('lotes', 'fecha_inicio')
    op.drop_column('lotes', 'tipo_gestion')
    op.drop_column('lotes', 'nombre_cultivo')
    op.drop_column('lotes', 'programa_id')
    op.drop_column('lotes', 'tipo_lote_id')
    op.add_column('labores', sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'labores', type_='foreignkey')
    op.drop_constraint(None, 'labores', type_='foreignkey')
    op.drop_constraint(None, 'labores', type_='foreignkey')
    op.create_foreign_key('labores_usuario_id_fkey', 'labores', 'usuarios', ['usuario_id'], ['id'])
    op.drop_column('labores', 'prioridad')
    op.drop_column('labores', 'fecha_asignacion')
    op.drop_column('labores', 'fecha_creacion')
    op.drop_column('labores', 'recomendacion_id')
    op.drop_column('labores', 'trabajador_id')
    op.drop_column('labores', 'tipo_labor_id')
    op.add_column('granjas', sa.Column('programa_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('granjas', sa.Column('asesor_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('granjas_programa_id_fkey', 'granjas', 'programas', ['programa_id'], ['id'])
    op.create_foreign_key('granjas_asesor_id_fkey', 'granjas', 'usuarios', ['asesor_id'], ['id'])
    op.drop_index(op.f('ix_movimientos_insumos_id'), table_name='movimientos_insumos')
    op.drop_table('movimientos_insumos')
    op.drop_index(op.f('ix_movimientos_herramientas_id'), table_name='movimientos_herramientas')
    op.drop_table('movimientos_herramientas')
    op.drop_table('usuario_programa')
    op.drop_table('usuario_granja')
    op.drop_index(op.f('ix_recomendaciones_id'), table_name='recomendaciones')
    op.drop_table('recomendaciones')
    op.drop_index(op.f('ix_insumos_id'), table_name='insumos')
    op.drop_table('insumos')
    op.drop_index(op.f('ix_herramientas_id'), table_name='herramientas')
    op.drop_table('herramientas')
    op.drop_table('granja_programa')
    op.drop_index(op.f('ix_tipos_lote_id'), table_name='tipos_lote')
    op.drop_table('tipos_lote')
    op.drop_index(op.f('ix_tipos_labor_id'), table_name='tipos_labor')
    op.drop_table('tipos_labor')
    op.drop_index(op.f('ix_categorias_inventario_id'), table_name='categorias_inventario')
    op.drop_table('categorias_inventario')
    # ### end Alembic commands ###
