"""agregar_sistema_roles

Revision ID: 4b2681de4270
Revises: cf4d0f223a27
Create Date: 2025-10-24 12:34:26.133131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b2681de4270'
down_revision: Union[str, None] = 'cf4d0f223a27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('nivel_permiso', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.add_column('granjas', sa.Column('activo', sa.Boolean(), nullable=True))
    op.add_column('granjas', sa.Column('fecha_creacion', sa.DateTime(), nullable=True))
    op.add_column('labores', sa.Column('descripcion', sa.String(length=255), nullable=True))
    op.add_column('lotes', sa.Column('fecha_creacion', sa.DateTime(), nullable=True))
    op.add_column('programas', sa.Column('activo', sa.Boolean(), nullable=True))
    op.add_column('usuarios', sa.Column('rol_id', sa.Integer(), nullable=False))
    op.add_column('usuarios', sa.Column('activo', sa.Boolean(), nullable=True))
    op.add_column('usuarios', sa.Column('fecha_creacion', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'usuarios', 'roles', ['rol_id'], ['id'])
    op.drop_column('usuarios', 'rol')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('rol', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.drop_column('usuarios', 'fecha_creacion')
    op.drop_column('usuarios', 'activo')
    op.drop_column('usuarios', 'rol_id')
    op.drop_column('programas', 'activo')
    op.drop_column('lotes', 'fecha_creacion')
    op.drop_column('labores', 'descripcion')
    op.drop_column('granjas', 'fecha_creacion')
    op.drop_column('granjas', 'activo')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
