"""actualizar_tabla_labores

Revision ID: 614365bf24de
Revises: fb55c723c1e2
Create Date: 2025-11-20 21:35:22.882959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '614365bf24de'
down_revision: Union[str, None] = 'fb55c723c1e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labores', sa.Column('tipo_labor_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'labores', 'tipos_labor', ['tipo_labor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'labores', type_='foreignkey')
    op.drop_column('labores', 'tipo_labor_id')
    # ### end Alembic commands ###
