"""Actualizar modelos Recomendacion y Labor

Revision ID: 6dca38b083de
Revises: 773cb03496cf
Create Date: 2025-10-31 18:32:55.927313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6dca38b083de'
down_revision: Union[str, None] = '773cb03496cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labores', sa.Column('comentario', sa.Text(), nullable=True))
    op.add_column('labores', sa.Column('fecha_finalizacion', sa.DateTime(), nullable=True))
    op.alter_column('labores', 'recomendacion_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('labores', 'trabajador_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('labores_tipo_labor_id_fkey', 'labores', type_='foreignkey')
    op.drop_column('labores', 'fecha_fin')
    op.drop_column('labores', 'fecha_inicio')
    op.drop_column('labores', 'fecha_creacion')
    op.drop_column('labores', 'tipo_labor_id')
    op.drop_column('labores', 'prioridad')
    op.drop_column('labores', 'descripcion')
    op.drop_column('labores', 'nombre')
    op.add_column('recomendaciones', sa.Column('tipo', sa.String(length=100), nullable=True))
    op.alter_column('recomendaciones', 'docente_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('recomendaciones', 'lote_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recomendaciones', 'lote_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('recomendaciones', 'docente_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('recomendaciones', 'tipo')
    op.add_column('labores', sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('labores', sa.Column('descripcion', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('labores', sa.Column('prioridad', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('labores', sa.Column('tipo_labor_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('labores', sa.Column('fecha_creacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('labores', sa.Column('fecha_inicio', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('labores', sa.Column('fecha_fin', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_foreign_key('labores_tipo_labor_id_fkey', 'labores', 'tipos_labor', ['tipo_labor_id'], ['id'])
    op.alter_column('labores', 'trabajador_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('labores', 'recomendacion_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('labores', 'fecha_finalizacion')
    op.drop_column('labores', 'comentario')
    # ### end Alembic commands ###
