"""fix fk relations

Revision ID: 763449a83a46
Revises: f1d72a1a079b
Create Date: 2025-10-31 15:44:46.626354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '763449a83a46'
down_revision: Union[str, None] = 'f1d72a1a079b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('granja_programa', 'granja_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('granja_programa', 'programa_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('labores', sa.Column('avance_porcentaje', sa.Integer(), nullable=True))
    op.add_column('recomendaciones', sa.Column('diagnostico_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'recomendaciones', 'diagnosticos', ['diagnostico_id'], ['id'])
    op.alter_column('usuario_granja', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('usuario_granja', 'granja_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('usuario_programa', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('usuario_programa', 'programa_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuario_programa', 'programa_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('usuario_programa', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('usuario_granja', 'granja_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('usuario_granja', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'recomendaciones', type_='foreignkey')
    op.drop_column('recomendaciones', 'diagnostico_id')
    op.drop_column('labores', 'avance_porcentaje')
    op.alter_column('granja_programa', 'programa_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('granja_programa', 'granja_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
