"""Creación de entidad de Cultivos/Especies.

Revision ID: 773cb03496cf
Revises: 763449a83a46
Create Date: 2025-10-31 17:05:34.536050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '773cb03496cf'
down_revision: Union[str, None] = '763449a83a46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cultivos_especies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('duracion_dias', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('granja_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['granja_id'], ['granjas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cultivos_especies_id'), 'cultivos_especies', ['id'], unique=False)
    op.add_column('lotes', sa.Column('cultivo_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'lotes', 'cultivos_especies', ['cultivo_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lotes', type_='foreignkey')
    op.drop_column('lotes', 'cultivo_id')
    op.drop_index(op.f('ix_cultivos_especies_id'), table_name='cultivos_especies')
    op.drop_table('cultivos_especies')
    # ### end Alembic commands ###
