"""Actualizacion de la tabla de usuario con authprovider

Revision ID: d0db7d921d58
Revises: 4e3cb414e7c4
Create Date: 2025-10-28 17:06:12.255478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0db7d921d58'
down_revision: Union[str, None] = '4e3cb414e7c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('auth_provider', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'auth_provider')
    # ### end Alembic commands ###
