"""Add Diagnostico + fix relaciones recomendacion/labor

Revision ID: f1d72a1a079b
Revises: d0db7d921d58
Create Date: 2025-10-30 18:44:22.949222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1d72a1a079b'
down_revision: Union[str, None] = 'd0db7d921d58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
