"""actualizar_tabla_evidencias

Revision ID: fb55c723c1e2
Revises: 7592b9ee95d3
Create Date: 2025-11-20 21:06:58.014415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb55c723c1e2'
down_revision: Union[str, None] = '7592b9ee95d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('url_archivo', sa.String(length=500), nullable=False),
    sa.Column('labor_id', sa.Integer(), nullable=True),
    sa.Column('diagnostico_id', sa.Integer(), nullable=True),
    sa.Column('recomendacion_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['diagnostico_id'], ['diagnosticos.id'], ),
    sa.ForeignKeyConstraint(['labor_id'], ['labores.id'], ),
    sa.ForeignKeyConstraint(['recomendacion_id'], ['recomendaciones.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidencias_id'), 'evidencias', ['id'], unique=False)
    op.drop_index('ix_evidencias_labor_id', table_name='evidencias_labor')
    op.drop_table('evidencias_labor')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidencias_labor',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('labor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('url_archivo', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('creado_por', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], name='evidencias_labor_creado_por_fkey'),
    sa.ForeignKeyConstraint(['labor_id'], ['labores.id'], name='evidencias_labor_labor_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='evidencias_labor_pkey')
    )
    op.create_index('ix_evidencias_labor_id', 'evidencias_labor', ['id'], unique=False)
    op.drop_index(op.f('ix_evidencias_id'), table_name='evidencias')
    op.drop_table('evidencias')
    # ### end Alembic commands ###
